vcs: git

prerequisites:
 - working-copy-check
 - display-last-changes
 - tests-check

version-generator: semantic

version-persister:
    vcs-tag:

post-release-actions:
    vcs-publish:
        ask-confirmation: true
